### ISSUE TITLE
dependence not found?

### ISSUE THREAD

**Issue by LXD312569496** [godaddy/compose-color-picker#16]
Could not find com.godaddy.android.colorpicker:compose-color-picker:0.4.1.

**Comment by ffgiraldez** [comment]
Hi @LXD312569496 

I can see it in [maven-central]( https://search.maven.org/artifact/com.godaddy.android.colorpicker/compose-color-picker-android/0.4.1/aar) do you use it in a multiplatform project or a regular android one?

**Comment by LXD312569496** [comment]
multiplatform project

**Comment by ffgiraldez** [comment]
could you please tell me which platforms are you targeting?

**Comment by riggaroo** [comment]
@LXD312569496 can you try ` com.godaddy.android.colorpicker:compose-color-picker-jvm:0.4.1` and let us know if you still see this issue?

**Comment by LXD312569496** [comment]
Hello！this is my code！
val commonMain by getting {
                implementation ("com.godaddy.android.colorpicker:compose-color-picker:0.3.1")
}

0.3.1 can work。
0.4.1 can not work，build failed。

**Comment by riggaroo** [comment]
Thanks for the report - we see the last build failed to release the `com.godaddy.android.colorpicker:compose-color-picker:0.4.1`. Since fixed the build, and `com.godaddy.android.colorpicker:compose-color-picker:0.4.2` should work. Please let us know if not. Thank you 🙏🏻

**Comment by LXD312569496** [comment]
ok
