### ISSUE TITLE
Make it multiplatform

### ISSUE THREAD

**Issue by JoseAlcerreca** [godaddy/compose-color-picker#2]
`Parcelize` and `android.graphics.Color` seem to be only blockers.

**Comment by riggaroo** [comment]
Made progress with @HuixingWong's PR, we just need to deploy correct artifacts to maven central now.

**Comment by riggaroo** [comment]
This should be working now with the latest release 0.2.1, please let us know if you experience any issues with it. It is our first exploration into multiplatform, so there might be some rough edges.
