### ISSUE TITLE
Setup Github actions to make releases

### ISSUE THREAD

**Issue by riggaroo** [godaddy/compose-color-picker#3]

**Comment by KelvnPere** [comment]
I haven't done this before though. But sounds like a very nice task to work on. Would you like me to contribute to this @riggaroo by learning on the job or its something internal you folks at godaddy are working on.

**Comment by riggaroo** [comment]
@KelvnPere So sorry - only saw your message now! I was just adding the task for myself to track. Unfortunately needed our godaddy maven central access to do it. 

I've since added the `.github/workflows/release.yml` that uploads to mavenCentral, used this article as a guide - https://proandroiddev.com/publishing-android-libraries-to-mavencentral-in-2021-8ac9975c3e52 and this plugin: 
https://github.com/vanniktech/gradle-maven-publish-plugin

Thanks for the interest, I'll be sure to safely watch these issues from now on 😄
