### ISSUE TITLE
Is this project being maintained? 

### ISSUE THREAD

**Issue by MessiasLima** [godaddy/compose-color-picker#74]
Is this project still being maintained? There are plenty of good improvements in the pull requests sections and the maintainers don't seem to be aware of it. This project is very useful and it's the best ColorPicker library so far. It would be sad if it was forgotten by the maintainers.

**Comment by ffranco-godaddy** [comment]
yes, but I'm a bit busy during my work hours and don't have too much spare time. But definitely is maintained as we use it in our apps.
